### ISSUE TITLE
Get to crackin' !

### ISSUE THREAD

**Issue by Sch3lp** [pxlit-projects/classroom-exercise-1-JasperSzkudlarski#1]
💪 
Ge zijt een van de weinigen die de oefening nog niet af heeft (of gepushed heeft).

**Comment by JasperSzkudlarski** [comment]
ja, sorry daarvoor, paar problemen tussen remote en local versie
(note to self, clone gewoon ipv de zip te downloaden)

**Comment by JasperSzkudlarski** [comment]
nieuwe clone gedaan, oplossing opnieuw gemaakt, should be fine now
